#!/bin/bash
# =============================================================================
# vps_setup.sh  -  Complete OVHcloud VPS setup for RaceIoT blockchain node
#
# Run this script ONCE on a fresh Ubuntu VPS:
#   chmod +x vps_setup.sh
#   sudo ./vps_setup.sh
#
# What this script does:
#   1. Installs Node.js 20
#   2. Creates a dedicated 'raceiot' user
#   3. Copies contract files to /opt/raceiot-blockchain
#   4. Installs Hardhat
#   5. Compiles contracts
#   6. Installs WireGuard VPN (VPS side) — gives RPi3 a static private IP
#   7. Configures firewall — port 8545 ONLY on WireGuard interface
#   8. Installs and starts hardhat-node.service (auto-start on boot)
#   9. Deploys contracts and prints blockchain.conf + RPi3 WireGuard config
#
# Why WireGuard instead of raw IP allowlist:
#   The RPi3 is behind home NAT — its public IP changes when the router
#   reconnects.  WireGuard gives the RPi3 a permanent private IP (10.99.0.2)
#   so port 8545 never needs to be exposed on the public interface at all.
# =============================================================================

set -e  # exit on any error

INSTALL_DIR="/opt/raceiot-blockchain"
SERVICE_USER="raceiot"
# WireGuard private network: VPS=10.99.0.1, RPi3=10.99.0.2
WG_VPS_IP="10.99.0.1"
WG_RPI_IP="10.99.0.2"
WG_PORT=51820   # UDP — one firewall port instead of exposing 8545 publicly

echo "=============================================="
echo "  RaceIoT VPS Setup  (WireGuard + Hardhat)"
echo "=============================================="

# ── Step 1: Install Node.js 20 LTS ───────────────────────────────────────────
echo ""
echo "[1/9] Installing Node.js 20 and WireGuard..."
apt update -qq
apt install -y curl ufw wireguard wireguard-tools
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt install -y nodejs
echo "  Node.js version: $(node --version)"
echo "  npm version:     $(npm --version)"
echo "  WireGuard:       $(wg --version)"

# ── Step 2: Create dedicated user ────────────────────────────────────────────
echo ""
echo "[2/9] Creating user '$SERVICE_USER'..."
if ! id "$SERVICE_USER" &>/dev/null; then
    useradd -m -s /bin/bash "$SERVICE_USER"
    echo "  Created user: $SERVICE_USER"
else
    echo "  User $SERVICE_USER already exists"
fi

# ── Step 3: Create install directory ─────────────────────────────────────────
echo ""
echo "[3/9] Setting up $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"

# Copy contract files (run from the directory containing this script)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cp "$SCRIPT_DIR"/*.sol             "$INSTALL_DIR/" 2>/dev/null || true
cp "$SCRIPT_DIR"/deploy.js         "$INSTALL_DIR/" 2>/dev/null || true
cp "$SCRIPT_DIR"/hardhat.config.js "$INSTALL_DIR/" 2>/dev/null || true
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"
echo "  Contract files copied to $INSTALL_DIR"

# ── Step 4: Install Hardhat ───────────────────────────────────────────────────
echo ""
echo "[4/9] Installing Hardhat (this takes ~1 minute)..."
cd "$INSTALL_DIR"
sudo -u "$SERVICE_USER" npm install --save-dev hardhat @nomicfoundation/hardhat-toolbox
echo "  Hardhat installed"

# ── Step 5: Compile contracts ─────────────────────────────────────────────────
echo ""
echo "[5/9] Compiling Solidity contracts..."
sudo -u "$SERVICE_USER" npx hardhat compile
echo "  Contracts compiled successfully"

# ── Step 6: Configure WireGuard VPN ──────────────────────────────────────────
echo ""
echo "[6/9] Configuring WireGuard VPN..."

WG_DIR="/etc/wireguard"
mkdir -p "$WG_DIR"
chmod 700 "$WG_DIR"

# Generate VPS keypair
wg genkey | tee "$WG_DIR/vps_private.key" | wg pubkey > "$WG_DIR/vps_public.key"
chmod 600 "$WG_DIR/vps_private.key"
VPS_PRIVATE_KEY=$(cat "$WG_DIR/vps_private.key")
VPS_PUBLIC_KEY=$(cat "$WG_DIR/vps_public.key")

# Generate RPi3 keypair (we generate it here; user copies it to RPi3)
wg genkey | tee "$WG_DIR/rpi3_private.key" | wg pubkey > "$WG_DIR/rpi3_public.key"
chmod 600 "$WG_DIR/rpi3_private.key"
RPI3_PRIVATE_KEY=$(cat "$WG_DIR/rpi3_private.key")
RPI3_PUBLIC_KEY=$(cat "$WG_DIR/rpi3_public.key")

# Get the main public-facing interface name (eth0, ens3, etc.)
PUBLIC_IFACE=$(ip route show default | awk '/default/ {print $5; exit}')
VPS_PUBLIC_IP=$(curl -s ifconfig.me 2>/dev/null || echo "<VPS-PUBLIC-IP>")

# Write VPS WireGuard config
cat > "$WG_DIR/wg0.conf" << EOF
# RaceIoT VPN — VPS side
# Auto-generated by vps_setup.sh on $(date)
[Interface]
Address    = ${WG_VPS_IP}/24
PrivateKey = ${VPS_PRIVATE_KEY}
ListenPort = ${WG_PORT}

# Forward masquerade so RPi3 can reach geth on 10.99.0.1:8545
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ${PUBLIC_IFACE} -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ${PUBLIC_IFACE} -j MASQUERADE

# --- RPi3 peer ---
[Peer]
PublicKey  = ${RPI3_PUBLIC_KEY}
AllowedIPs = ${WG_RPI_IP}/32
EOF
chmod 600 "$WG_DIR/wg0.conf"

# Enable IP forwarding
echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
sysctl -p > /dev/null 2>&1

# Enable WireGuard as a system service
systemctl enable wg-quick@wg0
systemctl start  wg-quick@wg0
echo "  WireGuard running  — VPS side: ${WG_VPS_IP}"
echo "  RPi3 will use:      ${WG_RPI_IP}"

# ── Step 7: Configure firewall ────────────────────────────────────────────────
echo ""
echo "[7/9] Configuring firewall..."
ufw allow 22/tcp       comment "SSH"
ufw allow "${WG_PORT}/udp" comment "WireGuard VPN"
# Port 8545 ONLY reachable from the WireGuard tunnel — never from public internet
ufw allow in on wg0 to any port 8545 proto tcp comment "Ethereum RPC via WireGuard only"
ufw deny  8545/tcp     comment "Block public Ethereum RPC"
ufw --force enable
echo "  Firewall rules:"
echo "    SSH    (22/tcp):        open to all"
echo "    VPN    (${WG_PORT}/udp): open to all (WireGuard handshake)"
echo "    RPC    (8545/tcp):      open on wg0 interface ONLY"
echo "    RPC    (8545/tcp):      BLOCKED on public interface"

# ── Step 8: Install and start hardhat-node.service ───────────────────────────
echo ""
echo "[8/9] Installing hardhat-node.service..."

# Write the systemd service file inline (not requiring a separate .service file)
cat > /etc/systemd/system/hardhat-node.service << EOF
[Unit]
Description=RaceIoT Hardhat Ethereum Node
After=network.target wg-quick@wg0.service
Requires=wg-quick@wg0.service

[Service]
Type=simple
User=${SERVICE_USER}
WorkingDirectory=${INSTALL_DIR}
# Bind Hardhat to the WireGuard interface IP — not 0.0.0.0
ExecStart=$(which npx) hardhat node --hostname ${WG_VPS_IP} --port 8545
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable hardhat-node.service
systemctl start  hardhat-node.service

echo "  Waiting for Hardhat node to start..."
sleep 6

if systemctl is-active --quiet hardhat-node.service; then
    echo "  hardhat-node.service is RUNNING on ${WG_VPS_IP}:8545"
else
    echo "  ERROR: hardhat-node.service failed to start"
    journalctl -u hardhat-node.service --no-pager -n 20
    exit 1
fi

# ── Step 9: Deploy contracts ──────────────────────────────────────────────────
echo ""
echo "[9/9] Deploying contracts to Hardhat node..."
cd "$INSTALL_DIR"

DEPLOY_OUTPUT=$(sudo -u "$SERVICE_USER" npx hardhat run deploy.js --network localhost 2>&1)
echo "$DEPLOY_OUTPUT"

AUTHLOG_ADDR=$(echo    "$DEPLOY_OUTPUT" | grep "IoTAuthLog deployed at"    | awk '{print $NF}')
COMMITREVEAL_ADDR=$(echo "$DEPLOY_OUTPUT" | grep "CommitRevealOTP deployed at" | awk '{print $NF}')
DEVICE_ADDR=$(echo     "$DEPLOY_OUTPUT" | grep "RPi3 device acct"          | awk '{print $NF}')

cat > "$INSTALL_DIR/deployed_addresses.txt" << EOF
# Deployed at: $(date)
AUTHLOG_CONTRACT=${AUTHLOG_ADDR}
COMMITREVEAL_CONTRACT=${COMMITREVEAL_ADDR}
DEVICE_ADDR=${DEVICE_ADDR}
EOF
chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR/deployed_addresses.txt"

# ── Print all outputs ─────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  SETUP COMPLETE"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "━━━━━  1 of 2: /etc/iot-gateway/blockchain.conf  on RPi3  ━━━━━"
echo ""
echo "  BLOCKCHAIN_RPC_URL=http://${WG_VPS_IP}:8545"
echo "  BLOCKCHAIN_AUTHLOG_CONTRACT=${AUTHLOG_ADDR}"
echo "  BLOCKCHAIN_COMMITREVEAL_CONTRACT=${COMMITREVEAL_ADDR}"
echo "  BLOCKCHAIN_DEVICE_ADDR=${DEVICE_ADDR}"
echo "  BLOCKCHAIN_CHAIN_ID=1337"
echo ""
echo "━━━━━  2 of 2: /etc/wireguard/wg0.conf  on RPi3  ━━━━━━━━━━━━━"
echo ""
echo "  [Interface]"
echo "  Address    = ${WG_RPI_IP}/24"
echo "  PrivateKey = ${RPI3_PRIVATE_KEY}"
echo ""
echo "  [Peer]"
echo "  PublicKey  = ${VPS_PUBLIC_KEY}"
echo "  Endpoint   = ${VPS_PUBLIC_IP}:${WG_PORT}"
echo "  AllowedIPs = ${WG_VPS_IP}/32"
echo "  PersistentKeepalive = 25"
echo ""
echo "  Then on RPi3 run:"
echo "    sudo systemctl enable --now wg-quick@wg0"
echo ""
echo "━━━━━  Useful VPS commands  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Check WireGuard peers:     sudo wg show"
echo "  Check Hardhat node:        systemctl status hardhat-node.service"
echo "  Watch live transactions:   journalctl -u hardhat-node.service -f"
echo "  Redeploy contracts:        cd ${INSTALL_DIR} && sudo -u ${SERVICE_USER} npx hardhat run deploy.js --network localhost"
echo ""
echo "════════════════════════════════════════════════════════════"


set -e  # exit on any error

# ── Argument check ────────────────────────────────────────────────────────────
if [ -z "$1" ]; then
    echo "Usage: sudo ./vps_setup.sh <RPi3-PUBLIC-IP>"
    echo "Example: sudo ./vps_setup.sh 82.45.123.67"
    exit 1
fi

RPI3_IP="$1"
INSTALL_DIR="/opt/raceiot-blockchain"
SERVICE_USER="raceiot"

echo "=============================================="
echo "  RaceIoT VPS Setup"
echo "  RPi3 IP: $RPI3_IP"
echo "=============================================="

# ── Step 1: Install Node.js 20 LTS ───────────────────────────────────────────
echo ""
echo "[1/8] Installing Node.js 20..."
apt update -qq
apt install -y curl ufw
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt install -y nodejs
echo "  Node.js version: $(node --version)"
echo "  npm version:     $(npm --version)"

# ── Step 2: Create dedicated user ────────────────────────────────────────────
echo ""
echo "[2/8] Creating user '$SERVICE_USER'..."
if ! id "$SERVICE_USER" &>/dev/null; then
    useradd -m -s /bin/bash "$SERVICE_USER"
    echo "  Created user: $SERVICE_USER"
else
    echo "  User $SERVICE_USER already exists"
fi

# ── Step 3: Create install directory ─────────────────────────────────────────
echo ""
echo "[3/8] Setting up $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"

# Copy contract files (run from the directory containing this script)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cp "$SCRIPT_DIR"/*.sol       "$INSTALL_DIR/" 2>/dev/null || true
cp "$SCRIPT_DIR"/deploy.js   "$INSTALL_DIR/" 2>/dev/null || true
cp "$SCRIPT_DIR"/hardhat.config.js "$INSTALL_DIR/" 2>/dev/null || true
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"
echo "  Contract files copied to $INSTALL_DIR"

# ── Step 4: Install Hardhat ───────────────────────────────────────────────────
echo ""
echo "[4/8] Installing Hardhat (this takes ~1 minute)..."
cd "$INSTALL_DIR"
sudo -u "$SERVICE_USER" npm install --save-dev hardhat @nomicfoundation/hardhat-toolbox
echo "  Hardhat installed"

# ── Step 5: Compile contracts ─────────────────────────────────────────────────
echo ""
echo "[5/8] Compiling Solidity contracts..."
sudo -u "$SERVICE_USER" npx hardhat compile
echo "  Contracts compiled successfully"

# ── Step 6: Configure firewall ────────────────────────────────────────────────
echo ""
echo "[6/8] Configuring firewall..."
# Always allow SSH first (critical — do not lock yourself out)
ufw allow 22/tcp comment "SSH"
# Allow RPi3 to reach Hardhat node
ufw allow from "$RPI3_IP" to any port 8545 proto tcp comment "RPi3 Ethereum RPC"
# Block everyone else from port 8545
ufw deny 8545/tcp comment "Block public Ethereum RPC"
# Enable firewall (non-interactive)
ufw --force enable
echo "  Firewall configured:"
echo "    - SSH (22): open to all"
echo "    - Port 8545: open to $RPI3_IP only"
echo "    - Port 8545: blocked for all others"

# ── Step 7: Install and start systemd service ─────────────────────────────────
echo ""
echo "[7/8] Installing hardhat-node.service..."
cp "$SCRIPT_DIR/hardhat-node.service" /etc/systemd/system/hardhat-node.service
# Update the WorkingDirectory in the service file
sed -i "s|WorkingDirectory=.*|WorkingDirectory=$INSTALL_DIR|" /etc/systemd/system/hardhat-node.service
systemctl daemon-reload
systemctl enable hardhat-node.service
systemctl start  hardhat-node.service

# Wait for Hardhat node to be ready
echo "  Waiting for Hardhat node to start..."
sleep 5

if systemctl is-active --quiet hardhat-node.service; then
    echo "  hardhat-node.service is RUNNING"
else
    echo "  ERROR: hardhat-node.service failed to start"
    journalctl -u hardhat-node.service --no-pager -n 20
    exit 1
fi

# ── Step 8: Deploy contracts ──────────────────────────────────────────────────
echo ""
echo "[8/8] Deploying contracts to local Hardhat node..."
cd "$INSTALL_DIR"

# Deploy and capture output
DEPLOY_OUTPUT=$(sudo -u "$SERVICE_USER" npx hardhat run deploy.js --network vps 2>&1)
echo "$DEPLOY_OUTPUT"

# Extract contract addresses from deploy output
AUTHLOG_ADDR=$(echo "$DEPLOY_OUTPUT" | grep "IoTAuthLog deployed at" | awk '{print $NF}')
COMMITREVEAL_ADDR=$(echo "$DEPLOY_OUTPUT" | grep "CommitRevealOTP deployed at" | awk '{print $NF}')
DEVICE_ADDR=$(echo "$DEPLOY_OUTPUT" | grep "RPi3 device acct" | awk '{print $NF}')

# Save addresses to a file for reference
cat > "$INSTALL_DIR/deployed_addresses.txt" << EOF
# Deployed at: $(date)
AUTHLOG_CONTRACT=$AUTHLOG_ADDR
COMMITREVEAL_CONTRACT=$COMMITREVEAL_ADDR
DEVICE_ADDR=$DEVICE_ADDR
EOF
chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR/deployed_addresses.txt"

# ── Print blockchain.conf for RPi3 ───────────────────────────────────────────
VPS_PUBLIC_IP=$(curl -s ifconfig.me 2>/dev/null || echo "<VPS-PUBLIC-IP>")

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  SETUP COMPLETE"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  Copy this into /etc/iot-gateway/blockchain.conf on the RPi3:"
echo ""
echo "  BLOCKCHAIN_RPC_URL=http://$VPS_PUBLIC_IP:8545"
echo "  BLOCKCHAIN_AUTHLOG_CONTRACT=$AUTHLOG_ADDR"
echo "  BLOCKCHAIN_COMMITREVEAL_CONTRACT=$COMMITREVEAL_ADDR"
echo "  BLOCKCHAIN_DEVICE_ADDR=$DEVICE_ADDR"
echo "  BLOCKCHAIN_CHAIN_ID=1337"
echo ""
echo "  Hardhat node status:"
echo "    systemctl status hardhat-node.service"
echo ""
echo "  View live blockchain transactions:"
echo "    journalctl -u hardhat-node.service -f"
echo "════════════════════════════════════════════════════════════"
